.catalog:
  name: master
  version: v1.0.0
  description: vote-demo-results
  uuid: master-0

vote-demo-results:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    healthy_threshold: 2
    response_timeout: 2000

vote-demo-results-app:
  scale: 1
  health_check:
    port: 8002
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000
